apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: keycloak-db-credentials
  data:
    - secretKey: db-user
      remoteRef:
        key: secret/data/api-security/keycloak-db
        property: username
    - secretKey: db-password
      remoteRef:
        key: secret/data/api-security/keycloak-db
        property: password
